my_string1=input("Какой сегодня день недели? ")
my_string2=input("Введи слово заклавными буквами: ")
my_string3=input("Был ли сегодня дождь? ")
print(len(my_string1))
print(my_string1. upper())
print(my_string2. lower())
print(my_string3. replace(' ', ""))
print(my_string3[0])
print(my_string3[-1])